export {
	type BrowserSupportContainer,
	type BrowserSupportEventType,
	type BrowserSupportHostOptions,
	type BrowserSupportRouteRegistry,
	type BrowserSupportStyleOptions,
	type BrowserSupportThemeMode,
	type BrowserSupportThemeOptions,
	type BrowserSupportWidget,
	type BrowserSupportWidgetOptions,
	type BrowserSupportWidgetRenderProps,
	type BrowserSupportWidgetState,
	type BrowserSupportWidgetUpdateOptions,
	mountSupportWidget,
} from "./mount-support-widget";
